version: '3.8'

services:
  pacaswap-node:
    image: constellationnetwork/pacaswap-node-operator
    container_name: pacaswap-node
    restart: unless-stopped
    
    ports:
      - "${METAGRAPH_L0_PUBLIC_PORT:-9100}:${METAGRAPH_L0_PUBLIC_PORT:-9100}"
      - "${METAGRAPH_L0_P2P_PORT:-9101}:${METAGRAPH_L0_P2P_PORT:-9101}"
      - "${METAGRAPH_L0_CLI_PORT:-9102}:${METAGRAPH_L0_CLI_PORT:-9102}"
      - "${CURRENCY_L1_PUBLIC_PORT:-9200}:${CURRENCY_L1_PUBLIC_PORT:-9200}"
      - "${CURRENCY_L1_P2P_PORT:-9201}:${CURRENCY_L1_P2P_PORT:-9201}"
      - "${CURRENCY_L1_CLI_PORT:-9202}:${CURRENCY_L1_CLI_PORT:-9202}"
      - "${DATA_L1_PUBLIC_PORT:-9300}:${DATA_L1_PUBLIC_PORT:-9300}"
      - "${DATA_L1_P2P_PORT:-9301}:${DATA_L1_P2P_PORT:-9301}"
      - "${DATA_L1_CLI_PORT:-9302}:${DATA_L1_CLI_PORT:-9302}"
    
    volumes:
      - ./shared-data:/app/shared-data
    
    environment:
      # My node info
      NODE_IP: ${NODE_IP}

      # Network Info
      ENVIRONMENT: ${ENVIRONMENT}
      GL0_NODE_IP: ${GL0_NODE_IP}
      GL0_NODE_PORT: ${GL0_NODE_PORT}
      GL0_NODE_ID: ${GL0_NODE_ID}

      # Metagraph Info
      METAGRAPH_ID: ${METAGRAPH_ID}
      LAYERS_TO_RUN: ${LAYERS_TO_RUN}

      SOURCE_NODE_1_IP: ${SOURCE_NODE_1_IP}
      SOURCE_NODE_1_ML0_PUBLIC_PORT: ${SOURCE_NODE_1_ML0_PUBLIC_PORT}
      SOURCE_NODE_1_ML0_P2P_PORT: ${SOURCE_NODE_1_ML0_P2P_PORT}
      SOURCE_NODE_1_CL1_PUBLIC_PORT: ${SOURCE_NODE_1_CL1_PUBLIC_PORT}
      SOURCE_NODE_1_CL1_P2P_PORT: ${SOURCE_NODE_1_CL1_P2P_PORT}
      SOURCE_NODE_1_DL1_PUBLIC_PORT: ${SOURCE_NODE_1_DL1_PUBLIC_PORT}
      SOURCE_NODE_1_DL1_P2P_PORT: ${SOURCE_NODE_1_DL1_P2P_PORT}
      SOURCE_NODE_1_PEER_ID:  ${SOURCE_NODE_1_PEER_ID}

      SOURCE_NODE_2_IP: ${SOURCE_NODE_2_IP}
      SOURCE_NODE_2_ML0_PUBLIC_PORT: ${SOURCE_NODE_2_ML0_PUBLIC_PORT}
      SOURCE_NODE_2_ML0_P2P_PORT: ${SOURCE_NODE_2_ML0_P2P_PORT}
      SOURCE_NODE_2_CL1_PUBLIC_PORT: ${SOURCE_NODE_2_CL1_PUBLIC_PORT}
      SOURCE_NODE_2_CL1_P2P_PORT: ${SOURCE_NODE_2_CL1_P2P_PORT}
      SOURCE_NODE_2_DL1_PUBLIC_PORT: ${SOURCE_NODE_2_DL1_PUBLIC_PORT}
      SOURCE_NODE_2_DL1_P2P_PORT: ${SOURCE_NODE_2_DL1_P2P_PORT}
      SOURCE_NODE_2_PEER_ID:  ${SOURCE_NODE_2_PEER_ID}

      SOURCE_NODE_3_IP: ${SOURCE_NODE_3_IP}
      SOURCE_NODE_3_ML0_PUBLIC_PORT: ${SOURCE_NODE_3_ML0_PUBLIC_PORT}
      SOURCE_NODE_3_ML0_P2P_PORT: ${SOURCE_NODE_3_ML0_P2P_PORT}
      SOURCE_NODE_3_CL1_PUBLIC_PORT: ${SOURCE_NODE_3_CL1_PUBLIC_PORT}
      SOURCE_NODE_3_CL1_P2P_PORT: ${SOURCE_NODE_3_CL1_P2P_PORT}
      SOURCE_NODE_3_DL1_PUBLIC_PORT: ${SOURCE_NODE_3_DL1_PUBLIC_PORT}
      SOURCE_NODE_3_DL1_P2P_PORT: ${SOURCE_NODE_3_DL1_P2P_PORT}
      SOURCE_NODE_3_PEER_ID:  ${SOURCE_NODE_3_PEER_ID}

      # Metagraph-L0 Variables
      METAGRAPH_L0_PUBLIC_PORT: ${METAGRAPH_L0_PUBLIC_PORT:-}
      METAGRAPH_L0_P2P_PORT: ${METAGRAPH_L0_P2P_PORT:-}
      METAGRAPH_L0_CLI_PORT: ${METAGRAPH_L0_CLI_PORT:-}
      METAGRAPH_L0_CL_KEYSTORE: ${METAGRAPH_L0_CL_KEYSTORE:-}
      METAGRAPH_L0_CL_KEYALIAS: ${METAGRAPH_L0_CL_KEYALIAS:-}
      METAGRAPH_L0_CL_PASSWORD: ${METAGRAPH_L0_CL_PASSWORD:-}
      METAGRAPH_L0_SEEDLIST_URL: ${METAGRAPH_L0_SEEDLIST_URL:-}
      METAGRAPH_L0_SEEDLIST_NAME: ${METAGRAPH_L0_SEEDLIST_NAME:-}
      METAGRAPH_L0_ALLOWANCE_LIST_URL: ${METAGRAPH_L0_ALLOWANCE_LIST_URL:-}
      METAGRAPH_L0_ALLOWANCE_LIST_NAME: ${METAGRAPH_L0_ALLOWANCE_LIST_NAME:-}
      
      # Currency-L1 Variables
      CURRENCY_L1_PUBLIC_PORT: ${CURRENCY_L1_PUBLIC_PORT:-}
      CURRENCY_L1_P2P_PORT: ${CURRENCY_L1_P2P_PORT:-}
      CURRENCY_L1_CLI_PORT: ${CURRENCY_L1_CLI_PORT:-}
      CURRENCY_L1_CL_KEYSTORE: ${CURRENCY_L1_CL_KEYSTORE:-}
      CURRENCY_L1_CL_KEYALIAS: ${CURRENCY_L1_CL_KEYALIAS:-}
      CURRENCY_L1_CL_PASSWORD: ${CURRENCY_L1_CL_PASSWORD:-}
      CURRENCY_L1_SEEDLIST_URL: ${CURRENCY_L1_SEEDLIST_URL:-}
      CURRENCY_L1_SEEDLIST_NAME: ${CURRENCY_L1_SEEDLIST_NAME:-}
      CURRENCY_L1_ALLOWANCE_LIST_URL: ${CURRENCY_L1_ALLOWANCE_LIST_URL:-}
      CURRENCY_L1_ALLOWANCE_LIST_NAME: ${CURRENCY_L1_ALLOWANCE_LIST_NAME:-}      

      # Data-L1 Variables
      DATA_L1_PUBLIC_PORT: ${DATA_L1_PUBLIC_PORT:-}
      DATA_L1_P2P_PORT: ${DATA_L1_P2P_PORT:-}
      DATA_L1_CLI_PORT: ${DATA_L1_CLI_PORT:-}
      DATA_L1_CL_KEYSTORE: ${DATA_L1_CL_KEYSTORE:-}
      DATA_L1_CL_KEYALIAS: ${DATA_L1_CL_KEYALIAS:-}
      DATA_L1_CL_PASSWORD: ${DATA_L1_CL_PASSWORD:-}
      DATA_L1_SEEDLIST_URL: ${DATA_L1_SEEDLIST_URL:-}
      DATA_L1_SEEDLIST_NAME: ${DATA_L1_SEEDLIST_NAME:-}
      DATA_L1_ALLOWANCE_LIST_URL: ${DATA_L1_ALLOWANCE_LIST_URL:-}
      DATA_L1_ALLOWANCE_LIST_NAME: ${DATA_L1_ALLOWANCE_LIST_NAME:-}